// Course content: kana tables plus the phrase / sentence / complex banks that
// back the "banked" chapters. Each banked theme holds 25+ items.

export const CHAPTERS = [
  { id: "hira", name: "Hiragana", caption: "The foundation. 46 core sounds.",
    units: [
      { jp: "あ", label: "Vowels", romaji: ["a", "i", "u", "e", "o"] },
      { jp: "か", label: "K row", romaji: ["ka", "ki", "ku", "ke", "ko"] },
      { jp: "さ", label: "S row", romaji: ["sa", "shi", "su", "se", "so"] },
      { jp: "た", label: "T row", romaji: ["ta", "chi", "tsu", "te", "to"] },
      { jp: "な", label: "N row", romaji: ["na", "ni", "nu", "ne", "no"] },
      { jp: "は", label: "H row", romaji: ["ha", "hi", "fu", "he", "ho"] },
      { jp: "ま", label: "M row", romaji: ["ma", "mi", "mu", "me", "mo"] },
      { jp: "や", label: "Y · R", romaji: ["ya", "yu", "yo", "ra", "ri"] },
      { jp: "わ", label: "W · ん", romaji: ["wa", "wo", "n"] },
      { jp: "総", label: "Review", romaji: [] },
    ] },
  { id: "kata", name: "Katakana", caption: "For loanwords and emphasis.",
    units: [
      { jp: "ア", label: "Vowels", romaji: ["a", "i", "u", "e", "o"] },
      { jp: "カ", label: "K row", romaji: ["ka", "ki", "ku", "ke", "ko"] },
      { jp: "サ", label: "S row", romaji: ["sa", "shi", "su", "se", "so"] },
      { jp: "タ", label: "T row", romaji: ["ta", "chi", "tsu", "te", "to"] },
      { jp: "ナ", label: "N row", romaji: ["na", "ni", "nu", "ne", "no"] },
      { jp: "ハ", label: "H row", romaji: ["ha", "hi", "fu", "he", "ho"] },
      { jp: "マ", label: "M row", romaji: ["ma", "mi", "mu", "me", "mo"] },
      { jp: "ヤ", label: "Y · R", romaji: ["ya", "yu", "yo", "ra", "ri"] },
      { jp: "ワ", label: "W · ン", romaji: ["wa", "wo", "n"] },
      { jp: "総", label: "Review", romaji: [] },
    ] },
  { id: "voiced", name: "Voiced sounds", caption: "Dakuten and handakuten.",
    units: [
      { jp: "が", label: "Hiragana", romaji: ["ga", "gi", "gu", "ge", "go"] },
      { jp: "ガ", label: "Katakana", romaji: ["ga", "gi", "gu", "ge", "go"] },
    ] },
  { id: "combo", name: "Combination sounds", caption: "Yōon glides like きゃ.",
    units: [
      { jp: "きゃ", label: "Hiragana", romaji: ["kya", "kyu", "kyo"] },
      { jp: "キャ", label: "Katakana", romaji: ["kya", "kyu", "kyo"] },
    ] },
  { id: "phrase", name: "Words and phrases", caption: "Everyday words across 14 themes.",
    units: [
      { jp: "挨", label: "Greetings", romaji: [] },
      { jp: "礼", label: "Politeness", romaji: [] },
      { jp: "食", label: "Food", romaji: [] },
      { jp: "道", label: "Travel", romaji: [] },
      { jp: "買", label: "Shopping", romaji: [] },
      { jp: "助", label: "Help", romaji: [] },
      { jp: "話", label: "Small talk", romaji: [] },
      { jp: "数", label: "Numbers", romaji: [] },
      { jp: "時", label: "Time & days", romaji: [] },
      { jp: "天", label: "Weather", romaji: [] },
      { jp: "心", label: "Feelings", romaji: [] },
      { jp: "家", label: "Family & friends", romaji: [] },
      { jp: "猫", label: "Animals & nature", romaji: [] },
      { jp: "色", label: "Colors", romaji: [] },
    ] },
  { id: "sentence", name: "Sentences", caption: "Simple everyday sentences.",
    units: [
      { jp: "私", label: "About me", romaji: [] },
      { jp: "問", label: "Questions", romaji: [] },
      { jp: "日", label: "Daily life", romaji: [] },
      { jp: "道", label: "Out & about", romaji: [] },
      { jp: "好", label: "Likes", romaji: [] },
      { jp: "飯", label: "Eating out", romaji: [] },
      { jp: "空", label: "Weather", romaji: [] },
      { jp: "友", label: "Friends & plans", romaji: [] },
      { jp: "助", label: "Getting help", romaji: [] },
      { jp: "店", label: "Shopping", romaji: [] },
      { jp: "旅", label: "Travel", romaji: [] },
    ] },
  { id: "complex", name: "Complex sentences", caption: "Longer sentences with more grammar.",
    units: [
      { jp: "見", label: "Opinions", romaji: [] },
      { jp: "昨", label: "Past & plans", romaji: [] },
      { jp: "繋", label: "Connected ideas", romaji: [] },
      { jp: "理", label: "Reasons", romaji: [] },
    ] },
];

export const PHRASE_IDX = CHAPTERS.findIndex((c) => c.id === "phrase");
export const SENTENCE_IDX = CHAPTERS.findIndex((c) => c.id === "sentence");

export const HIRA = {
  a: "あ", i: "い", u: "う", e: "え", o: "お",
  ka: "か", ki: "き", ku: "く", ke: "け", ko: "こ",
  sa: "さ", shi: "し", su: "す", se: "せ", so: "そ",
  ta: "た", chi: "ち", tsu: "つ", te: "て", to: "と",
  na: "な", ni: "に", nu: "ぬ", ne: "ね", no: "の",
  ha: "は", hi: "ひ", fu: "ふ", he: "へ", ho: "ほ",
  ma: "ま", mi: "み", mu: "む", me: "め", mo: "も",
  ya: "や", yu: "ゆ", yo: "よ",
  ra: "ら", ri: "り", ru: "る", re: "れ", ro: "ろ",
  wa: "わ", wo: "を", n: "ん",
  ga: "が", gi: "ぎ", gu: "ぐ", ge: "げ", go: "ご",
  kya: "きゃ", kyu: "きゅ", kyo: "きょ",
};
export const KATA = {
  a: "ア", i: "イ", u: "ウ", e: "エ", o: "オ",
  ka: "カ", ki: "キ", ku: "ク", ke: "ケ", ko: "コ",
  sa: "サ", shi: "シ", su: "ス", se: "セ", so: "ソ",
  ta: "タ", chi: "チ", tsu: "ツ", te: "テ", to: "ト",
  na: "ナ", ni: "ニ", nu: "ヌ", ne: "ネ", no: "ノ",
  ha: "ハ", hi: "ヒ", fu: "フ", he: "ヘ", ho: "ホ",
  ma: "マ", mi: "ミ", mu: "ム", me: "メ", mo: "モ",
  ya: "ヤ", yu: "ユ", yo: "ヨ",
  ra: "ラ", ri: "リ", ru: "ル", re: "レ", ro: "ロ",
  wa: "ワ", wo: "ヲ", n: "ン",
  ga: "ガ", gi: "ギ", gu: "グ", ge: "ゲ", go: "ゴ",
  kya: "キャ", kyu: "キュ", kyo: "キョ",
};

// Phrase / word bank keyed by theme unit index.
export const PHRASES = [
  [ // Greetings
    { jp: "こんにちは", romaji: "konnichiwa", en: "hello" },
    { jp: "おはよう", romaji: "ohayou", en: "good morning" },
    { jp: "おはようございます", romaji: "ohayou gozaimasu", en: "good morning (polite)" },
    { jp: "こんばんは", romaji: "konbanwa", en: "good evening" },
    { jp: "おやすみ", romaji: "oyasumi", en: "good night" },
    { jp: "おやすみなさい", romaji: "oyasuminasai", en: "good night (polite)" },
    { jp: "さようなら", romaji: "sayounara", en: "goodbye" },
    { jp: "またね", romaji: "matane", en: "see you" },
    { jp: "またあした", romaji: "mata ashita", en: "see you tomorrow" },
    { jp: "じゃあね", romaji: "jaane", en: "bye" },
    { jp: "はじめまして", romaji: "hajimemashite", en: "nice to meet you" },
    { jp: "おひさしぶり", romaji: "ohisashiburi", en: "long time no see" },
    { jp: "ようこそ", romaji: "youkoso", en: "welcome" },
    { jp: "おかえり", romaji: "okaeri", en: "welcome back" },
    { jp: "ただいま", romaji: "tadaima", en: "I'm home" },
    { jp: "いってきます", romaji: "ittekimasu", en: "I'm off" },
    { jp: "いってらっしゃい", romaji: "itterasshai", en: "see you off" },
    { jp: "げんきですか", romaji: "genki desu ka", en: "how are you?" },
    { jp: "おげんきですか", romaji: "ogenki desu ka", en: "how are you? (polite)" },
    { jp: "ひさしぶり", romaji: "hisashiburi", en: "it's been a while" },
    { jp: "やあ", romaji: "yaa", en: "hi" },
    { jp: "どうも", romaji: "doumo", en: "hi / thanks" },
    { jp: "よろしく", romaji: "yoroshiku", en: "nice to meet you" },
    { jp: "よろしくおねがいします", romaji: "yoroshiku onegaishimasu", en: "pleased to meet you (polite)" },
    { jp: "ごきげんよう", romaji: "gokigenyou", en: "good day (formal)" },
  ],
  [ // Politeness
    { jp: "ありがとう", romaji: "arigatou", en: "thank you" },
    { jp: "ありがとうございます", romaji: "arigatou gozaimasu", en: "thank you (polite)" },
    { jp: "どうもありがとう", romaji: "doumo arigatou", en: "thanks a lot" },
    { jp: "すみません", romaji: "sumimasen", en: "excuse me / sorry" },
    { jp: "ごめん", romaji: "gomen", en: "sorry" },
    { jp: "ごめんなさい", romaji: "gomennasai", en: "I'm sorry" },
    { jp: "おねがい", romaji: "onegai", en: "please" },
    { jp: "おねがいします", romaji: "onegaishimasu", en: "please (polite)" },
    { jp: "どうぞ", romaji: "douzo", en: "go ahead / here you are" },
    { jp: "どういたしまして", romaji: "douitashimashite", en: "you're welcome" },
    { jp: "だいじょうぶ", romaji: "daijoubu", en: "it's okay" },
    { jp: "だいじょうぶです", romaji: "daijoubu desu", en: "I'm fine" },
    { jp: "しつれいします", romaji: "shitsurei shimasu", en: "excuse me" },
    { jp: "おじゃまします", romaji: "ojama shimasu", en: "sorry to intrude" },
    { jp: "おそれいります", romaji: "osoreirimasu", en: "I'm much obliged" },
    { jp: "かまいません", romaji: "kamaimasen", en: "I don't mind" },
    { jp: "きにしないで", romaji: "ki ni shinaide", en: "don't worry about it" },
    { jp: "ありがとうございました", romaji: "arigatou gozaimashita", en: "thank you (past)" },
    { jp: "おつかれさま", romaji: "otsukaresama", en: "good work" },
    { jp: "おつかれさまです", romaji: "otsukaresama desu", en: "thanks for your work" },
    { jp: "いただきます", romaji: "itadakimasu", en: "thanks for the food" },
    { jp: "ごちそうさま", romaji: "gochisousama", en: "thanks for the meal" },
    { jp: "すみませんでした", romaji: "sumimasen deshita", en: "I'm sorry (past)" },
    { jp: "えんりょなく", romaji: "enryo naku", en: "please don't hold back" },
    { jp: "おまたせしました", romaji: "omatase shimashita", en: "sorry to keep you waiting" },
  ],
  [ // Food
    { jp: "ごはん", romaji: "gohan", en: "rice / meal" },
    { jp: "みず", romaji: "mizu", en: "water" },
    { jp: "おちゃ", romaji: "ocha", en: "tea" },
    { jp: "コーヒー", romaji: "koohii", en: "coffee" },
    { jp: "ぎゅうにゅう", romaji: "gyuunyuu", en: "milk" },
    { jp: "パン", romaji: "pan", en: "bread" },
    { jp: "たまご", romaji: "tamago", en: "egg" },
    { jp: "さかな", romaji: "sakana", en: "fish" },
    { jp: "にく", romaji: "niku", en: "meat" },
    { jp: "とりにく", romaji: "toriniku", en: "chicken" },
    { jp: "やさい", romaji: "yasai", en: "vegetables" },
    { jp: "くだもの", romaji: "kudamono", en: "fruit" },
    { jp: "りんご", romaji: "ringo", en: "apple" },
    { jp: "バナナ", romaji: "banana", en: "banana" },
    { jp: "みかん", romaji: "mikan", en: "mandarin" },
    { jp: "すし", romaji: "sushi", en: "sushi" },
    { jp: "ラーメン", romaji: "raamen", en: "ramen" },
    { jp: "うどん", romaji: "udon", en: "udon" },
    { jp: "そば", romaji: "soba", en: "soba" },
    { jp: "てんぷら", romaji: "tenpura", en: "tempura" },
    { jp: "カレー", romaji: "karee", en: "curry" },
    { jp: "おにぎり", romaji: "onigiri", en: "rice ball" },
    { jp: "みそしる", romaji: "misoshiru", en: "miso soup" },
    { jp: "おいしい", romaji: "oishii", en: "delicious" },
    { jp: "からい", romaji: "karai", en: "spicy" },
  ],
  [ // Travel
    { jp: "えき", romaji: "eki", en: "station" },
    { jp: "でんしゃ", romaji: "densha", en: "train" },
    { jp: "しんかんせん", romaji: "shinkansen", en: "bullet train" },
    { jp: "バス", romaji: "basu", en: "bus" },
    { jp: "タクシー", romaji: "takushii", en: "taxi" },
    { jp: "ひこうき", romaji: "hikouki", en: "airplane" },
    { jp: "くうこう", romaji: "kuukou", en: "airport" },
    { jp: "きっぷ", romaji: "kippu", en: "ticket" },
    { jp: "みち", romaji: "michi", en: "road" },
    { jp: "ちず", romaji: "chizu", en: "map" },
    { jp: "ホテル", romaji: "hoteru", en: "hotel" },
    { jp: "りょかん", romaji: "ryokan", en: "inn" },
    { jp: "みぎ", romaji: "migi", en: "right" },
    { jp: "ひだり", romaji: "hidari", en: "left" },
    { jp: "まっすぐ", romaji: "massugu", en: "straight ahead" },
    { jp: "ちかい", romaji: "chikai", en: "near" },
    { jp: "とおい", romaji: "tooi", en: "far" },
    { jp: "どこ", romaji: "doko", en: "where" },
    { jp: "こうばん", romaji: "kouban", en: "police box" },
    { jp: "にもつ", romaji: "nimotsu", en: "luggage" },
    { jp: "パスポート", romaji: "pasupooto", en: "passport" },
    { jp: "よやく", romaji: "yoyaku", en: "reservation" },
    { jp: "かんこう", romaji: "kankou", en: "sightseeing" },
    { jp: "うみ", romaji: "umi", en: "sea" },
    { jp: "やま", romaji: "yama", en: "mountain" },
  ],
  [ // Shopping
    { jp: "みせ", romaji: "mise", en: "shop" },
    { jp: "いくら", romaji: "ikura", en: "how much" },
    { jp: "おかね", romaji: "okane", en: "money" },
    { jp: "えん", romaji: "en", en: "yen" },
    { jp: "たかい", romaji: "takai", en: "expensive" },
    { jp: "やすい", romaji: "yasui", en: "cheap" },
    { jp: "これ", romaji: "kore", en: "this" },
    { jp: "それ", romaji: "sore", en: "that" },
    { jp: "あれ", romaji: "are", en: "that over there" },
    { jp: "おおきい", romaji: "ookii", en: "big" },
    { jp: "ちいさい", romaji: "chiisai", en: "small" },
    { jp: "いろ", romaji: "iro", en: "color" },
    { jp: "サイズ", romaji: "saizu", en: "size" },
    { jp: "レジ", romaji: "reji", en: "cashier" },
    { jp: "ふくろ", romaji: "fukuro", en: "bag" },
    { jp: "カード", romaji: "kaado", en: "card" },
    { jp: "げんきん", romaji: "genkin", en: "cash" },
    { jp: "りょうしゅうしょ", romaji: "ryoushuusho", en: "receipt" },
    { jp: "セール", romaji: "seeru", en: "sale" },
    { jp: "わりびき", romaji: "waribiki", en: "discount" },
    { jp: "かいます", romaji: "kaimasu", en: "I'll buy" },
    { jp: "ください", romaji: "kudasai", en: "please give me" },
    { jp: "みせて", romaji: "misete", en: "show me" },
    { jp: "しちゃく", romaji: "shichaku", en: "trying on" },
    { jp: "おつり", romaji: "otsuri", en: "change" },
  ],
  [ // Help
    { jp: "たすけて", romaji: "tasukete", en: "help" },
    { jp: "たすけてください", romaji: "tasukete kudasai", en: "please help me" },
    { jp: "だいじょうぶ", romaji: "daijoubu", en: "okay?" },
    { jp: "わかりません", romaji: "wakarimasen", en: "I don't understand" },
    { jp: "わかります", romaji: "wakarimasu", en: "I understand" },
    { jp: "しりません", romaji: "shirimasen", en: "I don't know" },
    { jp: "けいさつ", romaji: "keisatsu", en: "police" },
    { jp: "びょういん", romaji: "byouin", en: "hospital" },
    { jp: "きゅうきゅうしゃ", romaji: "kyuukyuusha", en: "ambulance" },
    { jp: "いしゃ", romaji: "isha", en: "doctor" },
    { jp: "くすり", romaji: "kusuri", en: "medicine" },
    { jp: "いたい", romaji: "itai", en: "it hurts" },
    { jp: "ぐあいがわるい", romaji: "guai ga warui", en: "I feel unwell" },
    { jp: "みちにまよった", romaji: "michi ni mayotta", en: "I'm lost" },
    { jp: "もういちど", romaji: "mou ichido", en: "one more time" },
    { jp: "ゆっくり", romaji: "yukkuri", en: "slowly" },
    { jp: "おねがい", romaji: "onegai", en: "please" },
    { jp: "だれか", romaji: "dareka", en: "someone" },
    { jp: "きをつけて", romaji: "ki o tsukete", en: "take care" },
    { jp: "あぶない", romaji: "abunai", en: "dangerous" },
    { jp: "とまって", romaji: "tomatte", en: "stop" },
    { jp: "てつだって", romaji: "tetsudatte", en: "help me out" },
    { jp: "こまっています", romaji: "komatte imasu", en: "I'm in trouble" },
    { jp: "でんわ", romaji: "denwa", en: "phone" },
    { jp: "えいご", romaji: "eigo", en: "English" },
  ],
  [ // Small talk
    { jp: "げんき", romaji: "genki", en: "well / energetic" },
    { jp: "たのしい", romaji: "tanoshii", en: "fun" },
    { jp: "うれしい", romaji: "ureshii", en: "happy" },
    { jp: "おもしろい", romaji: "omoshiroi", en: "interesting" },
    { jp: "すごい", romaji: "sugoi", en: "amazing" },
    { jp: "ほんとう", romaji: "hontou", en: "really" },
    { jp: "そうですね", romaji: "sou desu ne", en: "that's right" },
    { jp: "なるほど", romaji: "naruhodo", en: "I see" },
    { jp: "たぶん", romaji: "tabun", en: "maybe" },
    { jp: "もちろん", romaji: "mochiron", en: "of course" },
    { jp: "だいすき", romaji: "daisuki", en: "love it" },
    { jp: "きらい", romaji: "kirai", en: "dislike" },
    { jp: "すき", romaji: "suki", en: "like" },
    { jp: "いいね", romaji: "ii ne", en: "nice" },
    { jp: "だめ", romaji: "dame", en: "no good" },
    { jp: "ちょっと", romaji: "chotto", en: "a little" },
    { jp: "とても", romaji: "totemo", en: "very" },
    { jp: "すこし", romaji: "sukoshi", en: "a little" },
    { jp: "いつも", romaji: "itsumo", en: "always" },
    { jp: "ときどき", romaji: "tokidoki", en: "sometimes" },
    { jp: "あまり", romaji: "amari", en: "not much" },
    { jp: "ぜんぜん", romaji: "zenzen", en: "not at all" },
    { jp: "やっぱり", romaji: "yappari", en: "as expected" },
    { jp: "べつに", romaji: "betsuni", en: "nothing in particular" },
    { jp: "そうかな", romaji: "sou kana", en: "I wonder" },
  ],
  [ // Numbers
    { jp: "ゼロ", romaji: "zero", en: "zero" },
    { jp: "いち", romaji: "ichi", en: "one" },
    { jp: "に", romaji: "ni", en: "two" },
    { jp: "さん", romaji: "san", en: "three" },
    { jp: "よん", romaji: "yon", en: "four" },
    { jp: "ご", romaji: "go", en: "five" },
    { jp: "ろく", romaji: "roku", en: "six" },
    { jp: "なな", romaji: "nana", en: "seven" },
    { jp: "はち", romaji: "hachi", en: "eight" },
    { jp: "きゅう", romaji: "kyuu", en: "nine" },
    { jp: "じゅう", romaji: "juu", en: "ten" },
    { jp: "じゅういち", romaji: "juuichi", en: "eleven" },
    { jp: "じゅうに", romaji: "juuni", en: "twelve" },
    { jp: "じゅうさん", romaji: "juusan", en: "thirteen" },
    { jp: "じゅうよん", romaji: "juuyon", en: "fourteen" },
    { jp: "じゅうご", romaji: "juugo", en: "fifteen" },
    { jp: "にじゅう", romaji: "nijuu", en: "twenty" },
    { jp: "さんじゅう", romaji: "sanjuu", en: "thirty" },
    { jp: "よんじゅう", romaji: "yonjuu", en: "forty" },
    { jp: "ごじゅう", romaji: "gojuu", en: "fifty" },
    { jp: "ひゃく", romaji: "hyaku", en: "hundred" },
    { jp: "にひゃく", romaji: "nihyaku", en: "two hundred" },
    { jp: "せん", romaji: "sen", en: "thousand" },
    { jp: "まん", romaji: "man", en: "ten thousand" },
    { jp: "はんぶん", romaji: "hanbun", en: "half" },
  ],
  [ // Time & days
    { jp: "いま", romaji: "ima", en: "now" },
    { jp: "きょう", romaji: "kyou", en: "today" },
    { jp: "あした", romaji: "ashita", en: "tomorrow" },
    { jp: "きのう", romaji: "kinou", en: "yesterday" },
    { jp: "あさ", romaji: "asa", en: "morning" },
    { jp: "ひる", romaji: "hiru", en: "noon" },
    { jp: "よる", romaji: "yoru", en: "night" },
    { jp: "ばん", romaji: "ban", en: "evening" },
    { jp: "まいにち", romaji: "mainichi", en: "every day" },
    { jp: "しゅうまつ", romaji: "shuumatsu", en: "weekend" },
    { jp: "げつようび", romaji: "getsuyoubi", en: "Monday" },
    { jp: "かようび", romaji: "kayoubi", en: "Tuesday" },
    { jp: "すいようび", romaji: "suiyoubi", en: "Wednesday" },
    { jp: "もくようび", romaji: "mokuyoubi", en: "Thursday" },
    { jp: "きんようび", romaji: "kinyoubi", en: "Friday" },
    { jp: "どようび", romaji: "doyoubi", en: "Saturday" },
    { jp: "にちようび", romaji: "nichiyoubi", en: "Sunday" },
    { jp: "しゅう", romaji: "shuu", en: "week" },
    { jp: "つき", romaji: "tsuki", en: "month" },
    { jp: "とし", romaji: "toshi", en: "year" },
    { jp: "じかん", romaji: "jikan", en: "time / hour" },
    { jp: "ふん", romaji: "fun", en: "minute" },
    { jp: "びょう", romaji: "byou", en: "second" },
    { jp: "はやい", romaji: "hayai", en: "early / fast" },
    { jp: "おそい", romaji: "osoi", en: "late / slow" },
  ],
  [ // Weather
    { jp: "てんき", romaji: "tenki", en: "weather" },
    { jp: "はれ", romaji: "hare", en: "sunny" },
    { jp: "あめ", romaji: "ame", en: "rain" },
    { jp: "くもり", romaji: "kumori", en: "cloudy" },
    { jp: "ゆき", romaji: "yuki", en: "snow" },
    { jp: "かぜ", romaji: "kaze", en: "wind" },
    { jp: "あつい", romaji: "atsui", en: "hot" },
    { jp: "さむい", romaji: "samui", en: "cold" },
    { jp: "すずしい", romaji: "suzushii", en: "cool" },
    { jp: "あたたかい", romaji: "atatakai", en: "warm" },
    { jp: "むしあつい", romaji: "mushiatsui", en: "humid" },
    { jp: "たいふう", romaji: "taifuu", en: "typhoon" },
    { jp: "かみなり", romaji: "kaminari", en: "thunder" },
    { jp: "にじ", romaji: "niji", en: "rainbow" },
    { jp: "くも", romaji: "kumo", en: "cloud" },
    { jp: "そら", romaji: "sora", en: "sky" },
    { jp: "たいよう", romaji: "taiyou", en: "sun" },
    { jp: "つき", romaji: "tsuki", en: "moon" },
    { jp: "ほし", romaji: "hoshi", en: "star" },
    { jp: "きり", romaji: "kiri", en: "fog" },
    { jp: "こおり", romaji: "koori", en: "ice" },
    { jp: "あつさ", romaji: "atsusa", en: "heat" },
    { jp: "さむさ", romaji: "samusa", en: "coldness" },
    { jp: "きおん", romaji: "kion", en: "temperature" },
    { jp: "てんきよほう", romaji: "tenki yohou", en: "weather forecast" },
  ],
  [ // Feelings
    { jp: "うれしい", romaji: "ureshii", en: "happy" },
    { jp: "かなしい", romaji: "kanashii", en: "sad" },
    { jp: "たのしい", romaji: "tanoshii", en: "fun" },
    { jp: "さびしい", romaji: "sabishii", en: "lonely" },
    { jp: "こわい", romaji: "kowai", en: "scary" },
    { jp: "おこる", romaji: "okoru", en: "to get angry" },
    { jp: "びっくり", romaji: "bikkuri", en: "surprised" },
    { jp: "ねむい", romaji: "nemui", en: "sleepy" },
    { jp: "つかれた", romaji: "tsukareta", en: "tired" },
    { jp: "おなかすいた", romaji: "onaka suita", en: "hungry" },
    { jp: "のどがかわいた", romaji: "nodo ga kawaita", en: "thirsty" },
    { jp: "げんき", romaji: "genki", en: "energetic" },
    { jp: "しんぱい", romaji: "shinpai", en: "worried" },
    { jp: "あんしん", romaji: "anshin", en: "relieved" },
    { jp: "はずかしい", romaji: "hazukashii", en: "embarrassed" },
    { jp: "うらやましい", romaji: "urayamashii", en: "envious" },
    { jp: "たいくつ", romaji: "taikutsu", en: "bored" },
    { jp: "きんちょう", romaji: "kinchou", en: "nervous" },
    { jp: "こうふん", romaji: "koufun", en: "excited" },
    { jp: "まんぞく", romaji: "manzoku", en: "satisfied" },
    { jp: "ふあん", romaji: "fuan", en: "anxious" },
    { jp: "しあわせ", romaji: "shiawase", en: "happiness" },
    { jp: "きぶん", romaji: "kibun", en: "mood" },
    { jp: "すき", romaji: "suki", en: "fond" },
    { jp: "いやだ", romaji: "iya da", en: "unpleasant / no" },
  ],
  [ // Family & friends
    { jp: "かぞく", romaji: "kazoku", en: "family" },
    { jp: "おかあさん", romaji: "okaasan", en: "mother" },
    { jp: "おとうさん", romaji: "otousan", en: "father" },
    { jp: "あに", romaji: "ani", en: "older brother" },
    { jp: "あね", romaji: "ane", en: "older sister" },
    { jp: "おとうと", romaji: "otouto", en: "younger brother" },
    { jp: "いもうと", romaji: "imouto", en: "younger sister" },
    { jp: "そふ", romaji: "sofu", en: "grandfather" },
    { jp: "そぼ", romaji: "sobo", en: "grandmother" },
    { jp: "おじ", romaji: "oji", en: "uncle" },
    { jp: "おば", romaji: "oba", en: "aunt" },
    { jp: "こども", romaji: "kodomo", en: "child" },
    { jp: "むすこ", romaji: "musuko", en: "son" },
    { jp: "むすめ", romaji: "musume", en: "daughter" },
    { jp: "ともだち", romaji: "tomodachi", en: "friend" },
    { jp: "かれ", romaji: "kare", en: "boyfriend / him" },
    { jp: "かのじょ", romaji: "kanojo", en: "girlfriend / her" },
    { jp: "おっと", romaji: "otto", en: "husband" },
    { jp: "つま", romaji: "tsuma", en: "wife" },
    { jp: "あかちゃん", romaji: "akachan", en: "baby" },
    { jp: "りょうしん", romaji: "ryoushin", en: "parents" },
    { jp: "きょうだい", romaji: "kyoudai", en: "siblings" },
    { jp: "せんぱい", romaji: "senpai", en: "senior" },
    { jp: "こうはい", romaji: "kouhai", en: "junior" },
    { jp: "なかま", romaji: "nakama", en: "companion" },
  ],
  [ // Animals & nature
    { jp: "ねこ", romaji: "neko", en: "cat" },
    { jp: "いぬ", romaji: "inu", en: "dog" },
    { jp: "とり", romaji: "tori", en: "bird" },
    { jp: "さかな", romaji: "sakana", en: "fish" },
    { jp: "うま", romaji: "uma", en: "horse" },
    { jp: "うし", romaji: "ushi", en: "cow" },
    { jp: "ぶた", romaji: "buta", en: "pig" },
    { jp: "ひつじ", romaji: "hitsuji", en: "sheep" },
    { jp: "さる", romaji: "saru", en: "monkey" },
    { jp: "くま", romaji: "kuma", en: "bear" },
    { jp: "うさぎ", romaji: "usagi", en: "rabbit" },
    { jp: "ねずみ", romaji: "nezumi", en: "mouse" },
    { jp: "かえる", romaji: "kaeru", en: "frog" },
    { jp: "むし", romaji: "mushi", en: "insect" },
    { jp: "ちょう", romaji: "chou", en: "butterfly" },
    { jp: "き", romaji: "ki", en: "tree" },
    { jp: "はな", romaji: "hana", en: "flower" },
    { jp: "さくら", romaji: "sakura", en: "cherry blossom" },
    { jp: "やま", romaji: "yama", en: "mountain" },
    { jp: "かわ", romaji: "kawa", en: "river" },
    { jp: "うみ", romaji: "umi", en: "sea" },
    { jp: "そら", romaji: "sora", en: "sky" },
    { jp: "もり", romaji: "mori", en: "forest" },
    { jp: "くさ", romaji: "kusa", en: "grass" },
    { jp: "いし", romaji: "ishi", en: "stone" },
  ],
  [ // Colors
    { jp: "あか", romaji: "aka", en: "red" },
    { jp: "あお", romaji: "ao", en: "blue" },
    { jp: "きいろ", romaji: "kiiro", en: "yellow" },
    { jp: "みどり", romaji: "midori", en: "green" },
    { jp: "しろ", romaji: "shiro", en: "white" },
    { jp: "くろ", romaji: "kuro", en: "black" },
    { jp: "ちゃいろ", romaji: "chairo", en: "brown" },
    { jp: "むらさき", romaji: "murasaki", en: "purple" },
    { jp: "ピンク", romaji: "pinku", en: "pink" },
    { jp: "オレンジ", romaji: "orenji", en: "orange" },
    { jp: "はいいろ", romaji: "haiiro", en: "grey" },
    { jp: "きんいろ", romaji: "kiniro", en: "gold" },
    { jp: "ぎんいろ", romaji: "giniro", en: "silver" },
    { jp: "みずいろ", romaji: "mizuiro", en: "light blue" },
    { jp: "こん", romaji: "kon", en: "navy" },
    { jp: "ベージュ", romaji: "beeju", en: "beige" },
    { jp: "くりいろ", romaji: "kuriiro", en: "chestnut" },
    { jp: "あかるい", romaji: "akarui", en: "bright" },
    { jp: "くらい", romaji: "kurai", en: "dark" },
    { jp: "いろ", romaji: "iro", en: "color" },
    { jp: "カラフル", romaji: "karafuru", en: "colorful" },
    { jp: "とうめい", romaji: "toumei", en: "transparent" },
    { jp: "にじ", romaji: "niji", en: "rainbow" },
    { jp: "こい", romaji: "koi", en: "deep (color)" },
    { jp: "うすい", romaji: "usui", en: "pale" },
  ],
];

// Sentence bank keyed by the Sentences chapter's unit index.
export const SENTENCES = [
  [ // About me
    { jp: "わたしはがくせいです", romaji: "watashi wa gakusei desu", en: "I am a student" },
    { jp: "わたしはげんきです", romaji: "watashi wa genki desu", en: "I am well" },
    { jp: "にほんごをべんきょうします", romaji: "nihongo o benkyou shimasu", en: "I study Japanese" },
    { jp: "わたしのなまえはたなかです", romaji: "watashi no namae wa tanaka desu", en: "my name is Tanaka" },
    { jp: "にほんがすきです", romaji: "nihon ga suki desu", en: "I like Japan" },
    { jp: "ねこをかっています", romaji: "neko o katte imasu", en: "I have a cat" },
    { jp: "とうきょうにすんでいます", romaji: "toukyou ni sunde imasu", en: "I live in Tokyo" },
    { jp: "まいにちべんきょうします", romaji: "mainichi benkyou shimasu", en: "I study every day" },
    { jp: "おんがくがすきです", romaji: "ongaku ga suki desu", en: "I like music" },
    { jp: "コーヒーがすきです", romaji: "koohii ga suki desu", en: "I like coffee" },
    { jp: "あさはやくおきます", romaji: "asa hayaku okimasu", en: "I wake up early" },
    { jp: "ほんをよむのがすきです", romaji: "hon o yomu no ga suki desu", en: "I like reading books" },
    { jp: "えいごをはなします", romaji: "eigo o hanashimasu", en: "I speak English" },
    { jp: "かぞくはよにんです", romaji: "kazoku wa yonin desu", en: "my family is four people" },
    { jp: "いぬがすきです", romaji: "inu ga suki desu", en: "I like dogs" },
    { jp: "りょうりがすきです", romaji: "ryouri ga suki desu", en: "I like cooking" },
    { jp: "うみのちかくにすんでいます", romaji: "umi no chikaku ni sunde imasu", en: "I live near the sea" },
    { jp: "スポーツをします", romaji: "supootsu o shimasu", en: "I play sports" },
    { jp: "えいがをよくみます", romaji: "eiga o yoku mimasu", en: "I often watch movies" },
    { jp: "やまがすきです", romaji: "yama ga suki desu", en: "I like mountains" },
    { jp: "にほんにいきたいです", romaji: "nihon ni ikitai desu", en: "I want to go to Japan" },
    { jp: "まいにちあるきます", romaji: "mainichi arukimasu", en: "I walk every day" },
    { jp: "わたしはかいしゃいんです", romaji: "watashi wa kaishain desu", en: "I am an office worker" },
    { jp: "おちゃがすきです", romaji: "ocha ga suki desu", en: "I like tea" },
    { jp: "ともだちとあそびます", romaji: "tomodachi to asobimasu", en: "I hang out with friends" },
  ],
  [ // Questions
    { jp: "これはなんですか", romaji: "kore wa nan desu ka", en: "what is this?" },
    { jp: "えきはどこですか", romaji: "eki wa doko desu ka", en: "where is the station?" },
    { jp: "いまなんじですか", romaji: "ima nanji desu ka", en: "what time is it?" },
    { jp: "いくらですか", romaji: "ikura desu ka", en: "how much is it?" },
    { jp: "トイレはどこですか", romaji: "toire wa doko desu ka", en: "where is the toilet?" },
    { jp: "だれですか", romaji: "dare desu ka", en: "who is it?" },
    { jp: "なまえはなんですか", romaji: "namae wa nan desu ka", en: "what is your name?" },
    { jp: "どこからきましたか", romaji: "doko kara kimashita ka", en: "where are you from?" },
    { jp: "なにがすきですか", romaji: "nani ga suki desu ka", en: "what do you like?" },
    { jp: "これはなんといいますか", romaji: "kore wa nan to iimasu ka", en: "what is this called?" },
    { jp: "えいごをはなせますか", romaji: "eigo o hanasemasu ka", en: "can you speak English?" },
    { jp: "てつだってもらえますか", romaji: "tetsudatte moraemasu ka", en: "can you help me?" },
    { jp: "なんようびですか", romaji: "nanyoubi desu ka", en: "what day is it?" },
    { jp: "どうしてですか", romaji: "doushite desu ka", en: "why?" },
    { jp: "だいじょうぶですか", romaji: "daijoubu desu ka", en: "are you okay?" },
    { jp: "どこにいきますか", romaji: "doko ni ikimasu ka", en: "where are you going?" },
    { jp: "なにをしていますか", romaji: "nani o shite imasu ka", en: "what are you doing?" },
    { jp: "いつですか", romaji: "itsu desu ka", en: "when is it?" },
    { jp: "どれですか", romaji: "dore desu ka", en: "which one?" },
    { jp: "おいくつですか", romaji: "oikutsu desu ka", en: "how old are you?" },
    { jp: "どこにすんでいますか", romaji: "doko ni sunde imasu ka", en: "where do you live?" },
    { jp: "このでんしゃはとうきょうにいきますか", romaji: "kono densha wa toukyou ni ikimasu ka", en: "does this train go to Tokyo?" },
    { jp: "メニューはありますか", romaji: "menyuu wa arimasu ka", en: "do you have a menu?" },
    { jp: "しゃしんをとってもいいですか", romaji: "shashin o totte mo ii desu ka", en: "may I take a photo?" },
    { jp: "もういちどいってもらえますか", romaji: "mou ichido itte moraemasu ka", en: "can you say that again?" },
  ],
  [ // Daily life
    { jp: "ごはんをたべます", romaji: "gohan o tabemasu", en: "I eat a meal" },
    { jp: "みずをのみます", romaji: "mizu o nomimasu", en: "I drink water" },
    { jp: "あさろくじにおきます", romaji: "asa rokuji ni okimasu", en: "I wake up at six" },
    { jp: "よるじゅうじにねます", romaji: "yoru juuji ni nemasu", en: "I sleep at ten" },
    { jp: "ほんをよみます", romaji: "hon o yomimasu", en: "I read a book" },
    { jp: "テレビをみます", romaji: "terebi o mimasu", en: "I watch TV" },
    { jp: "おんがくをききます", romaji: "ongaku o kikimasu", en: "I listen to music" },
    { jp: "がっこうにいきます", romaji: "gakkou ni ikimasu", en: "I go to school" },
    { jp: "かいしゃにいきます", romaji: "kaisha ni ikimasu", en: "I go to work" },
    { jp: "うちにかえります", romaji: "uchi ni kaerimasu", en: "I return home" },
    { jp: "シャワーをあびます", romaji: "shawaa o abimasu", en: "I take a shower" },
    { jp: "はをみがきます", romaji: "ha o migakimasu", en: "I brush my teeth" },
    { jp: "あさごはんをたべます", romaji: "asagohan o tabemasu", en: "I eat breakfast" },
    { jp: "ひるごはんをたべます", romaji: "hirugohan o tabemasu", en: "I eat lunch" },
    { jp: "ばんごはんをたべます", romaji: "bangohan o tabemasu", en: "I eat dinner" },
    { jp: "そうじをします", romaji: "souji o shimasu", en: "I clean" },
    { jp: "せんたくをします", romaji: "sentaku o shimasu", en: "I do laundry" },
    { jp: "かいものをします", romaji: "kaimono o shimasu", en: "I go shopping" },
    { jp: "りょうりをします", romaji: "ryouri o shimasu", en: "I cook" },
    { jp: "コーヒーをのみます", romaji: "koohii o nomimasu", en: "I drink coffee" },
    { jp: "さんぽをします", romaji: "sanpo o shimasu", en: "I take a walk" },
    { jp: "でんしゃにのります", romaji: "densha ni norimasu", en: "I ride the train" },
    { jp: "しごとをします", romaji: "shigoto o shimasu", en: "I work" },
    { jp: "やすみます", romaji: "yasumimasu", en: "I rest" },
    { jp: "べんきょうします", romaji: "benkyou shimasu", en: "I study" },
  ],
  [ // Out & about
    { jp: "とうきょうにいきます", romaji: "toukyou ni ikimasu", en: "I'm going to Tokyo" },
    { jp: "みぎにまがってください", romaji: "migi ni magatte kudasai", en: "please turn right" },
    { jp: "ひだりにまがってください", romaji: "hidari ni magatte kudasai", en: "please turn left" },
    { jp: "まっすぐいってください", romaji: "massugu itte kudasai", en: "please go straight" },
    { jp: "ちょっとまってください", romaji: "chotto matte kudasai", en: "please wait a moment" },
    { jp: "えきまでおねがいします", romaji: "eki made onegaishimasu", en: "to the station, please" },
    { jp: "あるいていきます", romaji: "aruite ikimasu", en: "I'll walk there" },
    { jp: "でんしゃにのります", romaji: "densha ni norimasu", en: "I take the train" },
    { jp: "バスていはどこですか", romaji: "basutei wa doko desu ka", en: "where is the bus stop?" },
    { jp: "みちがわかりません", romaji: "michi ga wakarimasen", en: "I don't know the way" },
    { jp: "ここはどこですか", romaji: "koko wa doko desu ka", en: "where am I?" },
    { jp: "ちかくにありますか", romaji: "chikaku ni arimasu ka", en: "is it nearby?" },
    { jp: "このちかくにえきはありますか", romaji: "kono chikaku ni eki wa arimasu ka", en: "is there a station nearby?" },
    { jp: "タクシーをよんでください", romaji: "takushii o yonde kudasai", en: "please call a taxi" },
    { jp: "こうえんにいきます", romaji: "kouen ni ikimasu", en: "I'm going to the park" },
    { jp: "かいだんはどこですか", romaji: "kaidan wa doko desu ka", en: "where are the stairs?" },
    { jp: "エレベーターはどこですか", romaji: "erebeetaa wa doko desu ka", en: "where is the elevator?" },
    { jp: "でぐちはどこですか", romaji: "deguchi wa doko desu ka", en: "where is the exit?" },
    { jp: "いりぐちはどこですか", romaji: "iriguchi wa doko desu ka", en: "where is the entrance?" },
    { jp: "ちずをみせてください", romaji: "chizu o misete kudasai", en: "please show me a map" },
    { jp: "となりのまちにいきます", romaji: "tonari no machi ni ikimasu", en: "I'm going to the next town" },
    { jp: "じてんしゃでいきます", romaji: "jitensha de ikimasu", en: "I'll go by bicycle" },
    { jp: "くるまでいきます", romaji: "kuruma de ikimasu", en: "I'll go by car" },
    { jp: "もうすぐつきます", romaji: "mou sugu tsukimasu", en: "I'll arrive soon" },
    { jp: "みちをおしえてください", romaji: "michi o oshiete kudasai", en: "please tell me the way" },
  ],
  [ // Likes
    { jp: "ねこがすきです", romaji: "neko ga suki desu", en: "I like cats" },
    { jp: "いぬがすきです", romaji: "inu ga suki desu", en: "I like dogs" },
    { jp: "おんがくがすきです", romaji: "ongaku ga suki desu", en: "I like music" },
    { jp: "えいががすきです", romaji: "eiga ga suki desu", en: "I like movies" },
    { jp: "すしがだいすきです", romaji: "sushi ga daisuki desu", en: "I love sushi" },
    { jp: "ラーメンがすきです", romaji: "raamen ga suki desu", en: "I like ramen" },
    { jp: "コーヒーがすきです", romaji: "koohii ga suki desu", en: "I like coffee" },
    { jp: "おちゃがすきです", romaji: "ocha ga suki desu", en: "I like tea" },
    { jp: "ほんがすきです", romaji: "hon ga suki desu", en: "I like books" },
    { jp: "スポーツがすきです", romaji: "supootsu ga suki desu", en: "I like sports" },
    { jp: "りょこうがすきです", romaji: "ryokou ga suki desu", en: "I like travel" },
    { jp: "りょうりがすきです", romaji: "ryouri ga suki desu", en: "I like cooking" },
    { jp: "ゲームがすきです", romaji: "geemu ga suki desu", en: "I like games" },
    { jp: "さくらがすきです", romaji: "sakura ga suki desu", en: "I like cherry blossoms" },
    { jp: "うみがすきです", romaji: "umi ga suki desu", en: "I like the sea" },
    { jp: "やまがすきです", romaji: "yama ga suki desu", en: "I like mountains" },
    { jp: "なつがすきです", romaji: "natsu ga suki desu", en: "I like summer" },
    { jp: "ふゆがすきです", romaji: "fuyu ga suki desu", en: "I like winter" },
    { jp: "あめはすきじゃないです", romaji: "ame wa suki ja nai desu", en: "I don't like rain" },
    { jp: "やさいがすきです", romaji: "yasai ga suki desu", en: "I like vegetables" },
    { jp: "くだものがすきです", romaji: "kudamono ga suki desu", en: "I like fruit" },
    { jp: "チョコレートがすきです", romaji: "chokoreeto ga suki desu", en: "I like chocolate" },
    { jp: "にほんごがすきです", romaji: "nihongo ga suki desu", en: "I like Japanese" },
    { jp: "えがすきです", romaji: "e ga suki desu", en: "I like drawing" },
    { jp: "おんせんがすきです", romaji: "onsen ga suki desu", en: "I like hot springs" },
  ],
  [ // Eating out
    { jp: "みずをください", romaji: "mizu o kudasai", en: "water, please" },
    { jp: "メニューをください", romaji: "menyuu o kudasai", en: "the menu, please" },
    { jp: "おかいけいおねがいします", romaji: "okaikei onegaishimasu", en: "the bill, please" },
    { jp: "おいしかったです", romaji: "oishikatta desu", en: "it was delicious" },
    { jp: "これをください", romaji: "kore o kudasai", en: "this one, please" },
    { jp: "おすすめはなんですか", romaji: "osusume wa nan desu ka", en: "what do you recommend?" },
    { jp: "ふたりです", romaji: "futari desu", en: "two people" },
    { jp: "よやくがあります", romaji: "yoyaku ga arimasu", en: "I have a reservation" },
    { jp: "きんえんせきおねがいします", romaji: "kinenseki onegaishimasu", en: "non-smoking seat, please" },
    { jp: "おなじものをください", romaji: "onaji mono o kudasai", en: "I'll have the same" },
    { jp: "おみずをもういっぱい", romaji: "omizu o mou ippai", en: "another glass of water" },
    { jp: "からくしないでください", romaji: "karaku shinaide kudasai", en: "please don't make it spicy" },
    { jp: "ベジタリアンです", romaji: "bejitarian desu", en: "I'm vegetarian" },
    { jp: "アレルギーがあります", romaji: "arerugii ga arimasu", en: "I have an allergy" },
    { jp: "ちゅうもんおねがいします", romaji: "chuumon onegaishimasu", en: "I'd like to order" },
    { jp: "ビールをください", romaji: "biiru o kudasai", en: "a beer, please" },
    { jp: "おちゃをください", romaji: "ocha o kudasai", en: "tea, please" },
    { jp: "デザートはありますか", romaji: "dezaato wa arimasu ka", en: "do you have dessert?" },
    { jp: "もちかえりできますか", romaji: "mochikaeri dekimasu ka", en: "can I take it away?" },
    { jp: "おはしをください", romaji: "ohashi o kudasai", en: "chopsticks, please" },
    { jp: "すこしまってください", romaji: "sukoshi matte kudasai", en: "please wait a little" },
    { jp: "とてもおいしいです", romaji: "totemo oishii desu", en: "it's very delicious" },
    { jp: "ごちそうさまでした", romaji: "gochisousama deshita", en: "thank you for the meal" },
    { jp: "おなかがいっぱいです", romaji: "onaka ga ippai desu", en: "I'm full" },
    { jp: "テーブルせきおねがいします", romaji: "teeburu seki onegaishimasu", en: "a table seat, please" },
  ],
  [ // Weather
    { jp: "きょうはあついです", romaji: "kyou wa atsui desu", en: "it's hot today" },
    { jp: "きょうはさむいです", romaji: "kyou wa samui desu", en: "it's cold today" },
    { jp: "あめがふっています", romaji: "ame ga futte imasu", en: "it's raining" },
    { jp: "あしたははれです", romaji: "ashita wa hare desu", en: "tomorrow will be sunny" },
    { jp: "かぜがつよいです", romaji: "kaze ga tsuyoi desu", en: "the wind is strong" },
    { jp: "ゆきがふっています", romaji: "yuki ga futte imasu", en: "it's snowing" },
    { jp: "くもっています", romaji: "kumotte imasu", en: "it's cloudy" },
    { jp: "きょうはいいてんきです", romaji: "kyou wa ii tenki desu", en: "it's nice weather today" },
    { jp: "むしあついです", romaji: "mushiatsui desu", en: "it's humid" },
    { jp: "すずしくなりました", romaji: "suzushiku narimashita", en: "it's gotten cooler" },
    { jp: "あたたかいです", romaji: "atatakai desu", en: "it's warm" },
    { jp: "たいふうがきます", romaji: "taifuu ga kimasu", en: "a typhoon is coming" },
    { jp: "かみなりがなっています", romaji: "kaminari ga natte imasu", en: "it's thundering" },
    { jp: "そらがあおいです", romaji: "sora ga aoi desu", en: "the sky is blue" },
    { jp: "にじがでました", romaji: "niji ga demashita", en: "a rainbow appeared" },
    { jp: "あめがやみました", romaji: "ame ga yamimashita", en: "the rain has stopped" },
    { jp: "あしたはあめでしょう", romaji: "ashita wa ame deshou", en: "it will probably rain tomorrow" },
    { jp: "さむくなってきました", romaji: "samuku natte kimashita", en: "it's getting cold" },
    { jp: "ひがでています", romaji: "hi ga dete imasu", en: "the sun is out" },
    { jp: "きりがでています", romaji: "kiri ga dete imasu", en: "it's foggy" },
    { jp: "こんしゅうはあめがおおいです", romaji: "konshuu wa ame ga ooi desu", en: "there's a lot of rain this week" },
    { jp: "きおんがたかいです", romaji: "kion ga takai desu", en: "the temperature is high" },
    { jp: "きおんがひくいです", romaji: "kion ga hikui desu", en: "the temperature is low" },
    { jp: "てんきよほうをみます", romaji: "tenki yohou o mimasu", en: "I check the weather forecast" },
    { jp: "かさをもっていきます", romaji: "kasa o motte ikimasu", en: "I'll take an umbrella" },
  ],
  [ // Friends & plans
    { jp: "あしたあいましょう", romaji: "ashita aimashou", en: "let's meet tomorrow" },
    { jp: "いっしょにいきましょう", romaji: "issho ni ikimashou", en: "let's go together" },
    { jp: "えいがをみませんか", romaji: "eiga o mimasen ka", en: "shall we watch a movie?" },
    { jp: "またあした", romaji: "mata ashita", en: "see you tomorrow" },
    { jp: "たんじょうびおめでとう", romaji: "tanjoubi omedetou", en: "happy birthday" },
    { jp: "ごはんをたべにいきましょう", romaji: "gohan o tabe ni ikimashou", en: "let's go eat" },
    { jp: "なんじにあいますか", romaji: "nanji ni aimasu ka", en: "what time shall we meet?" },
    { jp: "どこであいますか", romaji: "doko de aimasu ka", en: "where shall we meet?" },
    { jp: "あそびにきてください", romaji: "asobi ni kite kudasai", en: "please come hang out" },
    { jp: "たのしみです", romaji: "tanoshimi desu", en: "I'm looking forward to it" },
    { jp: "こんしゅうまつはひまですか", romaji: "konshuumatsu wa hima desu ka", en: "are you free this weekend?" },
    { jp: "パーティーにきませんか", romaji: "paatii ni kimasen ka", en: "would you like to come to a party?" },
    { jp: "いっしょにたべませんか", romaji: "issho ni tabemasen ka", en: "shall we eat together?" },
    { jp: "カフェにいきましょう", romaji: "kafe ni ikimashou", en: "let's go to a cafe" },
    { jp: "れんらくしてください", romaji: "renraku shite kudasai", en: "please contact me" },
    { jp: "でんわしてください", romaji: "denwa shite kudasai", en: "please call me" },
    { jp: "またあとで", romaji: "mata atode", en: "see you later" },
    { jp: "よかったらきてください", romaji: "yokattara kite kudasai", en: "come if you'd like" },
    { jp: "ひさしぶりにあいたいです", romaji: "hisashiburi ni aitai desu", en: "I want to meet after a long time" },
    { jp: "あそびましょう", romaji: "asobimashou", en: "let's hang out" },
    { jp: "じゃあまた", romaji: "jaa mata", en: "see you then" },
    { jp: "よていはありますか", romaji: "yotei wa arimasu ka", en: "do you have plans?" },
    { jp: "あいましょうね", romaji: "aimashou ne", en: "let's meet, okay?" },
    { jp: "かいものにいきませんか", romaji: "kaimono ni ikimasen ka", en: "shall we go shopping?" },
    { jp: "おめでとうございます", romaji: "omedetou gozaimasu", en: "congratulations" },
  ],
  [ // Getting help
    { jp: "たすけてください", romaji: "tasukete kudasai", en: "please help me" },
    { jp: "みちにまよいました", romaji: "michi ni mayoimashita", en: "I'm lost" },
    { jp: "にほんごがすこしできます", romaji: "nihongo ga sukoshi dekimasu", en: "I speak a little Japanese" },
    { jp: "もういちどいってください", romaji: "mou ichido itte kudasai", en: "please say it again" },
    { jp: "えいごをはなせますか", romaji: "eigo o hanasemasu ka", en: "can you speak English?" },
    { jp: "ゆっくりはなしてください", romaji: "yukkuri hanashite kudasai", en: "please speak slowly" },
    { jp: "わかりません", romaji: "wakarimasen", en: "I don't understand" },
    { jp: "これをかいてください", romaji: "kore o kaite kudasai", en: "please write this down" },
    { jp: "びょういんはどこですか", romaji: "byouin wa doko desu ka", en: "where is the hospital?" },
    { jp: "けいさつをよんでください", romaji: "keisatsu o yonde kudasai", en: "please call the police" },
    { jp: "きゅうきゅうしゃをよんでください", romaji: "kyuukyuusha o yonde kudasai", en: "please call an ambulance" },
    { jp: "ぐあいがわるいです", romaji: "guai ga warui desu", en: "I feel unwell" },
    { jp: "あたまがいたいです", romaji: "atama ga itai desu", en: "I have a headache" },
    { jp: "おなかがいたいです", romaji: "onaka ga itai desu", en: "I have a stomachache" },
    { jp: "くすりがほしいです", romaji: "kusuri ga hoshii desu", en: "I want medicine" },
    { jp: "てつだってください", romaji: "tetsudatte kudasai", en: "please help me out" },
    { jp: "でんわをかしてください", romaji: "denwa o kashite kudasai", en: "please lend me a phone" },
    { jp: "みちをおしえてください", romaji: "michi o oshiete kudasai", en: "please show me the way" },
    { jp: "だいじょうぶですか", romaji: "daijoubu desu ka", en: "are you okay?" },
    { jp: "こまっています", romaji: "komatte imasu", en: "I'm in trouble" },
    { jp: "さいふをなくしました", romaji: "saifu o nakushimashita", en: "I lost my wallet" },
    { jp: "にもつがみつかりません", romaji: "nimotsu ga mitsukarimasen", en: "I can't find my luggage" },
    { jp: "たいしかんはどこですか", romaji: "taishikan wa doko desu ka", en: "where is the embassy?" },
    { jp: "えいごのメニューはありますか", romaji: "eigo no menyuu wa arimasu ka", en: "is there an English menu?" },
    { jp: "ちょっとてつだってもらえますか", romaji: "chotto tetsudatte moraemasu ka", en: "could you help me a bit?" },
  ],
  [ // Shopping
    { jp: "これはいくらですか", romaji: "kore wa ikura desu ka", en: "how much is this?" },
    { jp: "カードではらえますか", romaji: "kaado de haraemasu ka", en: "can I pay by card?" },
    { jp: "ふくろをください", romaji: "fukuro o kudasai", en: "a bag, please" },
    { jp: "たかすぎます", romaji: "takasugimasu", en: "it's too expensive" },
    { jp: "ちいさいサイズはありますか", romaji: "chiisai saizu wa arimasu ka", en: "do you have a small size?" },
    { jp: "おおきいサイズはありますか", romaji: "ookii saizu wa arimasu ka", en: "do you have a large size?" },
    { jp: "これをみせてください", romaji: "kore o misete kudasai", en: "please show me this" },
    { jp: "しちゃくしてもいいですか", romaji: "shichaku shite mo ii desu ka", en: "may I try it on?" },
    { jp: "ほかのいろはありますか", romaji: "hoka no iro wa arimasu ka", en: "do you have other colors?" },
    { jp: "もっとやすいのはありますか", romaji: "motto yasui no wa arimasu ka", en: "is there a cheaper one?" },
    { jp: "これをかいます", romaji: "kore o kaimasu", en: "I'll buy this" },
    { jp: "げんきんではらいます", romaji: "genkin de haraimasu", en: "I'll pay in cash" },
    { jp: "りょうしゅうしょをください", romaji: "ryoushuusho o kudasai", en: "a receipt, please" },
    { jp: "プレゼントようにつつんでください", romaji: "purezento you ni tsutsunde kudasai", en: "please gift-wrap it" },
    { jp: "セールはいつですか", romaji: "seeru wa itsu desu ka", en: "when is the sale?" },
    { jp: "これはなんですか", romaji: "kore wa nan desu ka", en: "what is this?" },
    { jp: "ためしてもいいですか", romaji: "tameshite mo ii desu ka", en: "may I try it?" },
    { jp: "どこではらいますか", romaji: "doko de haraimasu ka", en: "where do I pay?" },
    { jp: "おつりをください", romaji: "otsuri o kudasai", en: "change, please" },
    { jp: "あれをみせてください", romaji: "are o misete kudasai", en: "please show me that one" },
    { jp: "もうすこしやすくなりますか", romaji: "mou sukoshi yasuku narimasu ka", en: "can it be a little cheaper?" },
    { jp: "これとおなじものはありますか", romaji: "kore to onaji mono wa arimasu ka", en: "do you have the same as this?" },
    { jp: "しんぴんですか", romaji: "shinpin desu ka", en: "is it new?" },
    { jp: "へんぴんできますか", romaji: "henpin dekimasu ka", en: "can I return it?" },
    { jp: "これでおねがいします", romaji: "kore de onegaishimasu", en: "I'll take this" },
  ],
  [ // Travel
    { jp: "ホテルはどこですか", romaji: "hoteru wa doko desu ka", en: "where is the hotel?" },
    { jp: "きっぷをにまいください", romaji: "kippu o nimai kudasai", en: "two tickets, please" },
    { jp: "しゃしんをとってもいいですか", romaji: "shashin o totte mo ii desu ka", en: "may I take a photo?" },
    { jp: "くうこうまでおねがいします", romaji: "kuukou made onegaishimasu", en: "to the airport, please" },
    { jp: "かんこうにきました", romaji: "kankou ni kimashita", en: "I came for sightseeing" },
    { jp: "よやくがあります", romaji: "yoyaku ga arimasu", en: "I have a reservation" },
    { jp: "チェックインをおねがいします", romaji: "chekkuin o onegaishimasu", en: "check-in, please" },
    { jp: "へやをみせてください", romaji: "heya o misete kudasai", en: "please show me the room" },
    { jp: "にもつをあずかってください", romaji: "nimotsu o azukatte kudasai", en: "please hold my luggage" },
    { jp: "このでんしゃはどこにいきますか", romaji: "kono densha wa doko ni ikimasu ka", en: "where does this train go?" },
    { jp: "しんかんせんにのります", romaji: "shinkansen ni norimasu", en: "I'll take the bullet train" },
    { jp: "かたみちきっぷをください", romaji: "katamichi kippu o kudasai", en: "a one-way ticket, please" },
    { jp: "おうふくきっぷをください", romaji: "oufuku kippu o kudasai", en: "a round-trip ticket, please" },
    { jp: "なんじにつきますか", romaji: "nanji ni tsukimasu ka", en: "what time does it arrive?" },
    { jp: "このせきはあいていますか", romaji: "kono seki wa aite imasu ka", en: "is this seat free?" },
    { jp: "みやげをかいたいです", romaji: "miyage o kaitai desu", en: "I want to buy a souvenir" },
    { jp: "おすすめのばしょはどこですか", romaji: "osusume no basho wa doko desu ka", en: "what place do you recommend?" },
    { jp: "ちずをもらえますか", romaji: "chizu o moraemasu ka", en: "can I get a map?" },
    { jp: "ここでおりますか", romaji: "koko de orimasu ka", en: "do I get off here?" },
    { jp: "つぎのえきでおります", romaji: "tsugi no eki de orimasu", en: "I'll get off at the next station" },
    { jp: "りょこうがすきです", romaji: "ryokou ga suki desu", en: "I like traveling" },
    { jp: "おんせんにはいりたいです", romaji: "onsen ni hairitai desu", en: "I want to enter a hot spring" },
    { jp: "このちかくにみどころはありますか", romaji: "kono chikaku ni midokoro wa arimasu ka", en: "are there sights nearby?" },
    { jp: "にほんをりょこうしています", romaji: "nihon o ryokou shite imasu", en: "I'm traveling in Japan" },
    { jp: "たのしいたびでした", romaji: "tanoshii tabi deshita", en: "it was a fun trip" },
  ],
];

// Longer, multi-clause sentences for the Complex sentences chapter.
export const COMPLEX = [
  [ // Opinions
    { jp: "にほんごはむずかしいですが、たのしいです", romaji: "nihongo wa muzukashii desu ga, tanoshii desu", en: "Japanese is hard, but it's fun" },
    { jp: "このえいがはおもしろいとおもいます", romaji: "kono eiga wa omoshiroi to omoimasu", en: "I think this movie is interesting" },
    { jp: "なつよりふゆのほうがすきです", romaji: "natsu yori fuyu no hou ga suki desu", en: "I like winter more than summer" },
    { jp: "このレストランはたかいとおもいます", romaji: "kono resutoran wa takai to omoimasu", en: "I think this restaurant is expensive" },
    { jp: "わたしはそれがいいとおもいます", romaji: "watashi wa sore ga ii to omoimasu", en: "I think that's good" },
    { jp: "このほんはとてもおもしろかったです", romaji: "kono hon wa totemo omoshirokatta desu", en: "this book was very interesting" },
    { jp: "にほんのたべものはおいしいとおもいます", romaji: "nihon no tabemono wa oishii to omoimasu", en: "I think Japanese food is delicious" },
    { jp: "そのいけんにさんせいです", romaji: "sono iken ni sansei desu", en: "I agree with that opinion" },
    { jp: "わたしはそうおもいません", romaji: "watashi wa sou omoimasen", en: "I don't think so" },
    { jp: "このまちはしずかでいいです", romaji: "kono machi wa shizuka de ii desu", en: "this town is quiet and nice" },
    { jp: "このえいがよりあのえいがのほうがいいです", romaji: "kono eiga yori ano eiga no hou ga ii desu", en: "that movie is better than this one" },
    { jp: "にほんごのべんきょうはたいせつだとおもいます", romaji: "nihongo no benkyou wa taisetsu da to omoimasu", en: "I think studying Japanese is important" },
    { jp: "それはいいかんがえですね", romaji: "sore wa ii kangae desu ne", en: "that's a good idea" },
    { jp: "わたしはコーヒーよりおちゃがすきです", romaji: "watashi wa koohii yori ocha ga suki desu", en: "I prefer tea to coffee" },
    { jp: "このしごとはたいへんだけど、おもしろいです", romaji: "kono shigoto wa taihen da kedo, omoshiroi desu", en: "this job is tough but interesting" },
    { jp: "てんきがいいから、きもちがいいです", romaji: "tenki ga ii kara, kimochi ga ii desu", en: "the weather is nice so I feel good" },
    { jp: "このふくはたかいけど、すてきです", romaji: "kono fuku wa takai kedo, suteki desu", en: "these clothes are expensive but lovely" },
    { jp: "わたしはこのいろがいちばんすきです", romaji: "watashi wa kono iro ga ichiban suki desu", en: "I like this color the best" },
    { jp: "あのみせはサービスがいいとおもいます", romaji: "ano mise wa saabisu ga ii to omoimasu", en: "I think that shop has good service" },
    { jp: "このおんがくはすこしうるさいとおもいます", romaji: "kono ongaku wa sukoshi urusai to omoimasu", en: "I think this music is a bit loud" },
    { jp: "にほんはきれいなくにだとおもいます", romaji: "nihon wa kirei na kuni da to omoimasu", en: "I think Japan is a beautiful country" },
    { jp: "そのいけんはおもしろいですね", romaji: "sono iken wa omoshiroi desu ne", en: "that opinion is interesting" },
    { jp: "わたしにとってかぞくがいちばんたいせつです", romaji: "watashi ni totte kazoku ga ichiban taisetsu desu", en: "for me, family is the most important" },
    { jp: "このえはとてもうつくしいとおもいます", romaji: "kono e wa totemo utsukushii to omoimasu", en: "I think this painting is very beautiful" },
    { jp: "りょこうはたのしいけど、つかれます", romaji: "ryokou wa tanoshii kedo, tsukaremasu", en: "travel is fun but tiring" },
  ],
  [ // Past & plans
    { jp: "きのうともだちとえいがをみにいきました", romaji: "kinou tomodachi to eiga o mi ni ikimashita", en: "yesterday I went to see a movie with a friend" },
    { jp: "らいねんにほんへいきたいです", romaji: "rainen nihon e ikitai desu", en: "I want to go to Japan next year" },
    { jp: "しゅうまつはなにをしましたか", romaji: "shuumatsu wa nani o shimashita ka", en: "what did you do on the weekend?" },
    { jp: "きのうはうちでほんをよみました", romaji: "kinou wa uchi de hon o yomimashita", en: "yesterday I read a book at home" },
    { jp: "あしたともだちにあいます", romaji: "ashita tomodachi ni aimasu", en: "tomorrow I'll meet a friend" },
    { jp: "せんしゅうとうきょうにいきました", romaji: "senshuu toukyou ni ikimashita", en: "last week I went to Tokyo" },
    { jp: "こんばんえいがをみるつもりです", romaji: "konban eiga o miru tsumori desu", en: "I plan to watch a movie tonight" },
    { jp: "なつやすみにうみにいきました", romaji: "natsuyasumi ni umi ni ikimashita", en: "I went to the sea during summer break" },
    { jp: "きょねんにほんごをはじめました", romaji: "kyonen nihongo o hajimemashita", en: "I started Japanese last year" },
    { jp: "あしたははやくおきるつもりです", romaji: "ashita wa hayaku okiru tsumori desu", en: "I plan to wake up early tomorrow" },
    { jp: "せんしゅうまつはいそがしかったです", romaji: "senshuumatsu wa isogashikatta desu", en: "last weekend was busy" },
    { jp: "きのうおいしいラーメンをたべました", romaji: "kinou oishii raamen o tabemashita", en: "yesterday I ate delicious ramen" },
    { jp: "らいしゅうかいぎがあります", romaji: "raishuu kaigi ga arimasu", en: "there's a meeting next week" },
    { jp: "こどものとき、ピアノをならいました", romaji: "kodomo no toki, piano o naraimashita", en: "I learned piano as a child" },
    { jp: "あしたのよていはまだきめていません", romaji: "ashita no yotei wa mada kimete imasen", en: "I haven't decided tomorrow's plans yet" },
    { jp: "せんげつあたらしいしごとをはじめました", romaji: "sengetsu atarashii shigoto o hajimemashita", en: "I started a new job last month" },
    { jp: "このなつにほんをりょこうするつもりです", romaji: "kono natsu nihon o ryokou suru tsumori desu", en: "I plan to travel Japan this summer" },
    { jp: "きのうはよくねました", romaji: "kinou wa yoku nemashita", en: "I slept well yesterday" },
    { jp: "じゅぎょうのあとでかいものにいきました", romaji: "jugyou no ato de kaimono ni ikimashita", en: "after class I went shopping" },
    { jp: "らいげつともだちがきます", romaji: "raigetsu tomodachi ga kimasu", en: "a friend is coming next month" },
    { jp: "きのうのよるおそくまでべんきょうしました", romaji: "kinou no yoru osoku made benkyou shimashita", en: "I studied until late last night" },
    { jp: "ことしはたくさんりょこうしたいです", romaji: "kotoshi wa takusan ryokou shitai desu", en: "I want to travel a lot this year" },
    { jp: "このまえともだちとごはんをたべました", romaji: "kono mae tomodachi to gohan o tabemashita", en: "I ate with a friend the other day" },
    { jp: "あしたはやすみをとるつもりです", romaji: "ashita wa yasumi o toru tsumori desu", en: "I plan to take a day off tomorrow" },
    { jp: "せんじつにほんごのしけんをうけました", romaji: "senjitsu nihongo no shiken o ukemashita", en: "I took a Japanese exam the other day" },
  ],
  [ // Connected ideas
    { jp: "あさおきて、コーヒーをのみます", romaji: "asa okite, koohii o nomimasu", en: "I wake up and drink coffee" },
    { jp: "ほんをよんで、それからねます", romaji: "hon o yonde, sorekara nemasu", en: "I read a book and then sleep" },
    { jp: "でんしゃにのって、かいしゃにいきます", romaji: "densha ni notte, kaisha ni ikimasu", en: "I take the train and go to work" },
    { jp: "ごはんをたべて、はをみがきます", romaji: "gohan o tabete, ha o migakimasu", en: "I eat and brush my teeth" },
    { jp: "うちにかえって、テレビをみます", romaji: "uchi ni kaette, terebi o mimasu", en: "I go home and watch TV" },
    { jp: "シャワーをあびて、ねます", romaji: "shawaa o abite, nemasu", en: "I take a shower and sleep" },
    { jp: "かいものをして、りょうりをします", romaji: "kaimono o shite, ryouri o shimasu", en: "I shop and then cook" },
    { jp: "おきて、かおをあらいます", romaji: "okite, kao o araimasu", en: "I wake up and wash my face" },
    { jp: "えきにいって、きっぷをかいます", romaji: "eki ni itte, kippu o kaimasu", en: "I go to the station and buy a ticket" },
    { jp: "ともだちにあって、ごはんをたべました", romaji: "tomodachi ni atte, gohan o tabemashita", en: "I met a friend and ate" },
    { jp: "おんがくをききながら、べんきょうします", romaji: "ongaku o kikinagara, benkyou shimasu", en: "I study while listening to music" },
    { jp: "あるきながら、はなしましょう", romaji: "arukinagara, hanashimashou", en: "let's talk while walking" },
    { jp: "コーヒーをのみながら、ほんをよみます", romaji: "koohii o nominagara, hon o yomimasu", en: "I read while drinking coffee" },
    { jp: "あめがふって、さむくなりました", romaji: "ame ga futte, samuku narimashita", en: "it rained and got cold" },
    { jp: "やすんで、げんきになりました", romaji: "yasunde, genki ni narimashita", en: "I rested and got better" },
    { jp: "にほんごをべんきょうして、にほんへいきます", romaji: "nihongo o benkyou shite, nihon e ikimasu", en: "I study Japanese and go to Japan" },
    { jp: "へやをそうじして、せんたくをします", romaji: "heya o souji shite, sentaku o shimasu", en: "I clean the room and do laundry" },
    { jp: "あさごはんをたべて、がっこうにいきます", romaji: "asagohan o tabete, gakkou ni ikimasu", en: "I eat breakfast and go to school" },
    { jp: "えいがをみて、ごはんをたべました", romaji: "eiga o mite, gohan o tabemashita", en: "I watched a movie and ate" },
    { jp: "ふくをかって、カフェにいきました", romaji: "fuku o katte, kafe ni ikimashita", en: "I bought clothes and went to a cafe" },
    { jp: "しごとがおわって、いえにかえります", romaji: "shigoto ga owatte, ie ni kaerimasu", en: "work ends and I go home" },
    { jp: "てがみをかいて、おくりました", romaji: "tegami o kaite, okurimashita", en: "I wrote a letter and sent it" },
    { jp: "ちずをみて、みちをさがします", romaji: "chizu o mite, michi o sagashimasu", en: "I look at a map and find the way" },
    { jp: "おふろにはいって、すぐねました", romaji: "ofuro ni haitte, sugu nemashita", en: "I took a bath and slept right away" },
    { jp: "りょうりをして、ともだちとたべます", romaji: "ryouri o shite, tomodachi to tabemasu", en: "I cook and eat with friends" },
  ],
  [ // Reasons
    { jp: "あめがふっているから、いえにいます", romaji: "ame ga futte iru kara, ie ni imasu", en: "because it's raining, I'm staying home" },
    { jp: "つかれたから、はやくねます", romaji: "tsukareta kara, hayaku nemasu", en: "because I'm tired, I'll sleep early" },
    { jp: "にほんがすきだから、にほんごをべんきょうします", romaji: "nihon ga suki dakara, nihongo o benkyou shimasu", en: "because I like Japan, I study Japanese" },
    { jp: "おなかがすいたから、ごはんをたべます", romaji: "onaka ga suita kara, gohan o tabemasu", en: "because I'm hungry, I'll eat" },
    { jp: "さむいから、コートをきます", romaji: "samui kara, kooto o kimasu", en: "because it's cold, I'll wear a coat" },
    { jp: "いそがしいから、いけません", romaji: "isogashii kara, ikemasen", en: "because I'm busy, I can't go" },
    { jp: "あついから、まどをあけます", romaji: "atsui kara, mado o akemasu", en: "because it's hot, I'll open the window" },
    { jp: "おかねがないから、かいません", romaji: "okane ga nai kara, kaimasen", en: "because I have no money, I won't buy it" },
    { jp: "あしたしけんがあるから、べんきょうします", romaji: "ashita shiken ga aru kara, benkyou shimasu", en: "because there's an exam tomorrow, I'll study" },
    { jp: "ねむいから、コーヒーをのみます", romaji: "nemui kara, koohii o nomimasu", en: "because I'm sleepy, I'll drink coffee" },
    { jp: "じかんがないから、いそぎます", romaji: "jikan ga nai kara, isogimasu", en: "because there's no time, I'll hurry" },
    { jp: "びょうきだから、やすみます", romaji: "byouki dakara, yasumimasu", en: "because I'm sick, I'll rest" },
    { jp: "たのしいから、またいきたいです", romaji: "tanoshii kara, mata ikitai desu", en: "because it's fun, I want to go again" },
    { jp: "たかいから、かいませんでした", romaji: "takai kara, kaimasen deshita", en: "because it was expensive, I didn't buy it" },
    { jp: "すきだから、まいにちたべます", romaji: "suki dakara, mainichi tabemasu", en: "because I like it, I eat it every day" },
    { jp: "あぶないから、きをつけてください", romaji: "abunai kara, ki o tsukete kudasai", en: "because it's dangerous, please be careful" },
    { jp: "でんしゃがおくれたから、ちこくしました", romaji: "densha ga okureta kara, chikoku shimashita", en: "because the train was late, I was late" },
    { jp: "おいしいから、このみせがすきです", romaji: "oishii kara, kono mise ga suki desu", en: "because it's delicious, I like this shop" },
    { jp: "さむくなったから、まどをしめます", romaji: "samuku natta kara, mado o shimemasu", en: "because it got cold, I'll close the window" },
    { jp: "あしたはやすみだから、おそくまでおきます", romaji: "ashita wa yasumi dakara, osoku made okimasu", en: "because tomorrow's a day off, I'll stay up late" },
    { jp: "わからないから、ゆっくりはなしてください", romaji: "wakaranai kara, yukkuri hanashite kudasai", en: "because I don't understand, please speak slowly" },
    { jp: "みちがわからないから、ちずをみます", romaji: "michi ga wakaranai kara, chizu o mimasu", en: "because I don't know the way, I'll look at a map" },
    { jp: "おもしろいから、このほんがすきです", romaji: "omoshiroi kara, kono hon ga suki desu", en: "because it's interesting, I like this book" },
    { jp: "あめだから、かさをもっていきます", romaji: "ame dakara, kasa o motte ikimasu", en: "because it's raining, I'll take an umbrella" },
    { jp: "げんきになったから、しごとにいきます", romaji: "genki ni natta kara, shigoto ni ikimasu", en: "because I've recovered, I'll go to work" },
  ],
];

// Banked chapters draw their lessons from a bank instead of the kana tables.
export const BANKS = { phrase: PHRASES, sentence: SENTENCES, complex: COMPLEX };

// Numbers — practice-only, grouped the way Japanese numbers are usually taught:
// the 1-10 base, the teens, the tens, hundreds (with 300/600/800 sound changes),
// thousands (3000/8000 changes), and man-based large numbers. `en` is the digit.
export const NUMBER_GROUPS = [
  { id: "ones", label: "1–10", jp: "一", items: [
    { jp: "ゼロ", romaji: "zero", en: "0" },
    { jp: "いち", romaji: "ichi", en: "1" },
    { jp: "に", romaji: "ni", en: "2" },
    { jp: "さん", romaji: "san", en: "3" },
    { jp: "よん", romaji: "yon", en: "4" },
    { jp: "ご", romaji: "go", en: "5" },
    { jp: "ろく", romaji: "roku", en: "6" },
    { jp: "なな", romaji: "nana", en: "7" },
    { jp: "はち", romaji: "hachi", en: "8" },
    { jp: "きゅう", romaji: "kyuu", en: "9" },
    { jp: "じゅう", romaji: "juu", en: "10" },
  ] },
  { id: "teens", label: "11–19", jp: "十", items: [
    { jp: "じゅういち", romaji: "juuichi", en: "11" },
    { jp: "じゅうに", romaji: "juuni", en: "12" },
    { jp: "じゅうさん", romaji: "juusan", en: "13" },
    { jp: "じゅうよん", romaji: "juuyon", en: "14" },
    { jp: "じゅうご", romaji: "juugo", en: "15" },
    { jp: "じゅうろく", romaji: "juuroku", en: "16" },
    { jp: "じゅうなな", romaji: "juunana", en: "17" },
    { jp: "じゅうはち", romaji: "juuhachi", en: "18" },
    { jp: "じゅうきゅう", romaji: "juukyuu", en: "19" },
  ] },
  { id: "tens", label: "Tens", jp: "卄", items: [
    { jp: "にじゅう", romaji: "nijuu", en: "20" },
    { jp: "さんじゅう", romaji: "sanjuu", en: "30" },
    { jp: "よんじゅう", romaji: "yonjuu", en: "40" },
    { jp: "ごじゅう", romaji: "gojuu", en: "50" },
    { jp: "ろくじゅう", romaji: "rokujuu", en: "60" },
    { jp: "ななじゅう", romaji: "nanajuu", en: "70" },
    { jp: "はちじゅう", romaji: "hachijuu", en: "80" },
    { jp: "きゅうじゅう", romaji: "kyuujuu", en: "90" },
  ] },
  { id: "hundreds", label: "Hundreds", jp: "百", items: [
    { jp: "ひゃく", romaji: "hyaku", en: "100" },
    { jp: "にひゃく", romaji: "nihyaku", en: "200" },
    { jp: "さんびゃく", romaji: "sanbyaku", en: "300" },
    { jp: "よんひゃく", romaji: "yonhyaku", en: "400" },
    { jp: "ごひゃく", romaji: "gohyaku", en: "500" },
    { jp: "ろっぴゃく", romaji: "roppyaku", en: "600" },
    { jp: "ななひゃく", romaji: "nanahyaku", en: "700" },
    { jp: "はっぴゃく", romaji: "happyaku", en: "800" },
    { jp: "きゅうひゃく", romaji: "kyuuhyaku", en: "900" },
  ] },
  { id: "thousands", label: "Thousands", jp: "千", items: [
    { jp: "せん", romaji: "sen", en: "1,000" },
    { jp: "にせん", romaji: "nisen", en: "2,000" },
    { jp: "さんぜん", romaji: "sanzen", en: "3,000" },
    { jp: "よんせん", romaji: "yonsen", en: "4,000" },
    { jp: "ごせん", romaji: "gosen", en: "5,000" },
    { jp: "ろくせん", romaji: "rokusen", en: "6,000" },
    { jp: "ななせん", romaji: "nanasen", en: "7,000" },
    { jp: "はっせん", romaji: "hassen", en: "8,000" },
    { jp: "きゅうせん", romaji: "kyuusen", en: "9,000" },
  ] },
  { id: "big", label: "10,000+", jp: "万", items: [
    { jp: "いちまん", romaji: "ichiman", en: "10,000" },
    { jp: "じゅうまん", romaji: "juuman", en: "100,000" },
    { jp: "ひゃくまん", romaji: "hyakuman", en: "1,000,000" },
    { jp: "せんまん", romaji: "senman", en: "10,000,000" },
    { jp: "いちおく", romaji: "ichioku", en: "100,000,000" },
  ] },
];

// Read-through explainer shown from the Sentences card ("Read the basics").
export const SENTENCE_BASICS = [
  { title: "Word order: subject → object → verb",
    body: "Japanese puts the verb last. The subject and object come first, each tagged by a small “particle” word.",
    ex: { jp: "わたしはすしをたべます", romaji: "watashi wa sushi o tabemasu", en: "I eat sushi (lit. “I sushi eat”)" } },
  { title: "Particles tag each word's job",
    body: "Tiny words after a noun show its role: は topic, を object, が subject, に to/at, で by/at, の possessive, と with, も also, から from, まで until.",
    ex: null },
  { title: "は · を · が",
    body: "は (wa) marks the topic — what the sentence is about. を (o) marks the object the action affects. が (ga) marks the subject, often new or in focus.",
    ex: { jp: "ねこがすきです", romaji: "neko ga suki desu", en: "(I) like cats" } },
  { title: "Sentence endings",
    body: "です = is/am/are (polite). ます = polite verb ending. Add か to ask a question, ね for “…, right?”, よ to stress or inform.",
    ex: { jp: "たべますか", romaji: "tabemasu ka", en: "Will (you) eat? — か makes it a question" } },
  { title: "Dropped pronouns",
    body: "Japanese leaves out “I / you / it” when context makes them obvious. The same words can mean “I…”, “you…”, and so on.",
    ex: { jp: "わかりました", romaji: "wakarimashita", en: "(I) understood" } },
];

// Grammar quiz items for the Practice "Sentence foundations" set. Each is
// multiple-choice; `meaning` is the explanation revealed after answering.
export const FOUNDATIONS = [
  { prompt: "Japanese word order is usually…", options: ["Subject–Object–Verb", "Subject–Verb–Object", "Verb–Subject–Object", "Object–Verb–Subject"], answer: "Subject–Object–Verb", meaning: "The verb comes last: わたしはすしをたべます." },
  { prompt: "Which particle marks the topic?", ex: "わたし＿ がくせいです", options: ["は", "を", "が", "に"], answer: "は", meaning: "は (wa) marks the topic: “As for me, …”." },
  { prompt: "Which particle marks the object?", ex: "すし＿ たべます", options: ["を", "は", "で", "へ"], answer: "を", meaning: "を (o) marks the object the verb acts on." },
  { prompt: "Which particle marks the subject?", ex: "だれ＿ きましたか", options: ["が", "は", "を", "の"], answer: "が", meaning: "が marks the subject, often new/unknown info: “Who came?”." },
  { prompt: "Which ending turns a statement into a question?", options: ["か", "ね", "よ", "です"], answer: "か", meaning: "か at the end makes a question: たべますか." },
  { prompt: "「です」 means…", options: ["is / am / are", "to go", "not", "and"], answer: "is / am / are", meaning: "です is the polite copula (“to be”)." },
  { prompt: "「たべます」 is a…", options: ["polite present verb", "past verb", "noun", "question"], answer: "polite present verb", meaning: "ます makes a verb polite, present/future." },
  { prompt: "Which particle means “to / at a place”?", ex: "がっこう＿ いきます", options: ["に", "を", "は", "も"], answer: "に", meaning: "に marks destination or time: “go to school”." },
  { prompt: "Which particle means “with / and”?", ex: "ともだち＿ いきます", options: ["と", "を", "が", "の"], answer: "と", meaning: "と means “with” (or “and” between nouns)." },
  { prompt: "Who likes cats here?", ex: "ねこがすきです", options: ["I (implied)", "the cat", "you only", "nobody"], answer: "I (implied)", meaning: "Japanese drops “I/you” when clear: “(I) like cats”." },
  { prompt: "Which ending softly seeks agreement (“…, right?”)?", options: ["ね", "か", "よ", "を"], answer: "ね", meaning: "ね invites agreement: いいてんきですね." },
  { prompt: "Which ending adds emphasis / new info?", options: ["よ", "か", "の", "は"], answer: "よ", meaning: "よ emphasizes or informs: いきますよ." },
  { prompt: "Which particle shows possession?", ex: "わたし＿ ほん", options: ["の", "を", "に", "が"], answer: "の", meaning: "の links nouns: わたしのほん = my book." },
  { prompt: "Which particle means “also / too”?", ex: "わたし＿ いきます", options: ["も", "は", "を", "で"], answer: "も", meaning: "も = “also”: “I will go too”." },
  { prompt: "Which particle marks means / place of action?", ex: "バス＿ いきます", options: ["で", "に", "を", "へ"], answer: "で", meaning: "で marks how/where: “go by bus”." },
  { prompt: "Why does 「わかりました」 need no “I”?", options: ["The subject is implied", "It's a command", "It's plural", "It's a question"], answer: "The subject is implied", meaning: "Pronouns are dropped when obvious: “(I) understood”." },
  { prompt: "Which particle means “from”?", ex: "とうきょう＿ きました", options: ["から", "まで", "に", "で"], answer: "から", meaning: "から = “from”: “came from Tokyo”." },
  { prompt: "Which particle means “until / as far as”?", ex: "えき＿ あるきます", options: ["まで", "から", "を", "へ"], answer: "まで", meaning: "まで = “until / as far as”: “walk to the station”." },
];

// ---- learner profile (onboarding) ----
export function loadProfile() {
  try {
    const v = JSON.parse(localStorage.getItem("hk-profile-v1"));
    if (v && typeof v === "object") return v;
  } catch (e) {}
  return null;
}
export function saveProfile(p) {
  try { localStorage.setItem("hk-profile-v1", JSON.stringify(p)); } catch (e) {}
}

// Onboarding answer → words used in the personalised sentences.
export const COUNTRIES = {
  australia: { kana: "オーストラリア", roma: "oosutoraria", en: "Australia" },
  uk: { kana: "イギリス", roma: "igirisu", en: "the UK" },
  usa: { kana: "アメリカ", roma: "amerika", en: "the US" },
  canada: { kana: "カナダ", roma: "kanada", en: "Canada" },
  newzealand: { kana: "ニュージーランド", roma: "nyuujiirando", en: "New Zealand" },
  japan: { kana: "にほん", roma: "nihon", en: "Japan" },
};
export const HOBBIES = {
  music: { kana: "おんがく", roma: "ongaku", en: "music" },
  sports: { kana: "スポーツ", roma: "supootsu", en: "sports" },
  reading: { kana: "どくしょ", roma: "dokusho", en: "reading" },
  games: { kana: "ゲーム", roma: "geemu", en: "games" },
  cooking: { kana: "りょうり", roma: "ryouri", en: "cooking" },
  travel: { kana: "りょこう", roma: "ryokou", en: "travel" },
};

const LIKES_IDX = 4;

const NUM_KANA = ["", "いち", "に", "さん", "よん", "ご", "ろく", "なな", "はち", "きゅう"];
const NUM_ROMA = ["", "ichi", "ni", "san", "yon", "go", "roku", "nana", "hachi", "kyuu"];

// 1-99 as "...さい", with the standard sound changes (いっさい, はっさい, じゅっさい).
function ageWords(n) {
  if (!n || n < 1 || n > 99) return null;
  const tens = Math.floor(n / 10), units = n % 10;
  let kana = "", roma = "";
  if (tens) { kana += (tens > 1 ? NUM_KANA[tens] : "") + "じゅう"; roma += (tens > 1 ? NUM_ROMA[tens] : "") + "juu"; }
  if (units) { kana += NUM_KANA[units]; roma += NUM_ROMA[units]; }
  if (units === 1) { kana = kana.slice(0, -2) + "いっ"; roma = roma.slice(0, -4) + "is"; }
  else if (units === 8) { kana = kana.slice(0, -2) + "はっ"; roma = roma.slice(0, -5) + "has"; }
  else if (!units && tens) { kana = kana.slice(0, -3) + "じゅっ"; roma = roma.slice(0, -3) + "jus"; }
  return { kana: kana + "さい", roma: roma + "sai" };
}

function ageFromDob(dob) {
  const d = new Date(dob);
  if (isNaN(d)) return null;
  const now = new Date();
  let a = now.getFullYear() - d.getFullYear();
  const m = now.getMonth() - d.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < d.getDate())) a--;
  return a;
}

// The About me unit reflects the learner's onboarding answers when available.
export function aboutMeSentences() {
  const p = loadProfile();
  if (!p || p.skipped) return SENTENCES[0];
  const out = [
    { jp: "わたしはげんきです", romaji: "watashi wa genki desu", en: "I am well" },
    { jp: "にほんごをべんきょうします", romaji: "nihongo o benkyou shimasu", en: "I study Japanese" },
  ];
  if (p.name) out.push({ jp: `わたしのなまえは${p.name}です`, romaji: `watashi no namae wa ${p.name} desu`, en: `My name is ${p.name}` });
  const age = p.dob ? ageFromDob(p.dob) : null;
  const aw = ageWords(age);
  if (aw) out.push({ jp: `わたしは${aw.kana}です`, romaji: `watashi wa ${aw.roma} desu`, en: `I am ${age} years old` });
  const c = p.country && COUNTRIES[p.country];
  if (c) out.push({ jp: `${c.kana}からきました`, romaji: `${c.roma} kara kimashita`, en: `I'm from ${c.en}` });
  if (p.pets === "cat") out.push({ jp: "ねこをかっています", romaji: "neko o katte imasu", en: "I have a cat" });
  else if (p.pets === "dog") out.push({ jp: "いぬをかっています", romaji: "inu o katte imasu", en: "I have a dog" });
  else if (p.pets === "both") out.push({ jp: "ねこといぬをかっています", romaji: "neko to inu o katte imasu", en: "I have a cat and a dog" });
  else if (p.pets === "none") out.push({ jp: "ペットはいません", romaji: "petto wa imasen", en: "I don't have pets" });
  if (p.occupation === "study") out.push({ jp: "わたしはがくせいです", romaji: "watashi wa gakusei desu", en: "I am a student" });
  else if (p.occupation === "work") out.push({ jp: "はたらいています", romaji: "hataraite imasu", en: "I work" });
  // pad to 25 with general About me lines the learner hasn't already got
  for (const s of SENTENCES[0]) {
    if (out.length >= 25) break;
    if (!out.some((o) => o.romaji === s.romaji)) out.push(s);
  }
  return out;
}

// The Likes unit leads with the learner's chosen hobbies (multi-select).
export function likesSentences() {
  const p = loadProfile();
  const base = SENTENCES[LIKES_IDX];
  const picks = p && !p.skipped && Array.isArray(p.hobbies) ? p.hobbies : [];
  const mine = picks.map((h) => HOBBIES[h]).filter(Boolean)
    .map((h) => ({ jp: `${h.kana}がすきです`, romaji: `${h.roma} ga suki desu`, en: `I like ${h.en}` }));
  const seen = new Set(mine.map((m) => m.romaji));
  return [...mine, ...base.filter((s) => !seen.has(s.romaji))];
}

// Bank lookup with personalised Sentences units swapped in.
export const bankFor = (chapterId) => {
  if (chapterId === "sentence") {
    const b = SENTENCES.slice();
    b[0] = aboutMeSentences();
    b[LIKES_IDX] = likesSentences();
    return b;
  }
  return BANKS[chapterId];
};
